local:
  server:
    port: 8080
  postgre:
    dsn: "host=localhost user=postgres password=secret dbname=mydb port=5432 sslmode=disable"
  security:
    jwtSecretKey: "supersecretmykey"
    minutesOfJwtExpiration: 15
    hoursOfRefreshTokenExpiration: 24
  otel_trace_endpoint: "192.168.1.5:4318"

prod:
  server:
    port: 8080
  postgre:
    dsn: "host=postgres user=postgres password=secret dbname=mydb port=5432 sslmode=disable"
  security:
    jwtSecretKey: "supersecretmykey"
    minutesOfJwtExpiration: 15
    hoursOfRefreshTokenExpiration: 24
  otel_trace_endpoint: "192.168.1.5:4318"