### Healthcheck
GET http://localhost:8080/healthcheck
Accept: application/json

### Create User
POST http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "firstName": "Mehmet",
  "lastName": "Solak",
  "email": "mehmet@example.com",
  "password": "secret123"
}

### Get User by ID
GET http://localhost:8080/users/42bc5fe1-c4b8-437d-bbf6-d06a23099a50
Accept: application/json

### Get User List
GET http://localhost:8080/users/
Accept: application/json