### Healthcheck
GET http://localhost:8080/healthcheck
Accept: application/json

### Create User
POST http://localhost:8080/users
Content-Type: application/json
Accept: application/json

{
  "firstName": "Ahmet",
  "lastName": "Yildirim",
  "email": "ahmet@example.com",
  "password": "secret123"
}

### Get User by ID
GET http://localhost:8080/users/42bc5fe1-c4b8-437d-bbf6-d06a23099a50
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFobWV0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzU5OTUyNTg5LCJmdWxsTmFtZSI6IkFobWV0IFlpbGRpcmltIiwic3ViIjoiYzIxNDYzZDAtNzgzZS00YzhjLWIyMGYtMmNkZDAzYWNlMjZmIn0.prv4Y2n-tscMEhQ3PTGuRhEWBUEl5l1HJ_PQz83n4b4

### Get User List
GET http://localhost:8080/users/
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFobWV0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzU5OTUyNTg5LCJmdWxsTmFtZSI6IkFobWV0IFlpbGRpcmltIiwic3ViIjoiYzIxNDYzZDAtNzgzZS00YzhjLWIyMGYtMmNkZDAzYWNlMjZmIn0.prv4Y2n-tscMEhQ3PTGuRhEWBUEl5l1HJ_PQz83n4b4

### Login
POST http://localhost:8080/login/
Content-Type: application/json
Accept: application/json

{
  "email": "ahmet@example.com",
  "password": "secret123"
}

### ME
GET http://localhost:8080/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFobWV0QGV4YW1wbGUuY29tIiwiZXhwIjoxNzU5OTUyNTg5LCJmdWxsTmFtZSI6IkFobWV0IFlpbGRpcmltIiwic3ViIjoiYzIxNDYzZDAtNzgzZS00YzhjLWIyMGYtMmNkZDAzYWNlMjZmIn0.prv4Y2n-tscMEhQ3PTGuRhEWBUEl5l1HJ_PQz83n4b4
